language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --features test_without_hardware
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libbluetooth-dev
